if (GMP_LIBRARIES AND GMP_INCLUDE_DIRS)
  set (GMP_FIND_QUIETLY TRUE)
endif (GMP_LIBRARIES AND GMP_INCLUDE_DIRS)

find_path(GMP_INCLUDE_DIRS NAMES gmp.h)
find_path(GMPXX_INCLUDE_DIR NAMES gmpxx.h)
find_library(GMP_LIBRARIES NAMES gmp)
find_library(GMPXX_LIBRARY NAMES gmpxx)




include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GMP DEFAULT_MSG
  GMP_LIBRARIES GMPXX_LIBRARY GMPXX_INCLUDE_DIR
  GMP_INCLUDE_DIRS)

LIST(APPEND GMP_LIBRARIES ${GMPXX_LIBRARY})
LIST(APPEND GMP_INCLUDE_DIRS ${GMPXX_INCLUDE_DIR})


unset(GMPXX_LIBRARY)
unset(GMPXX_INCLUDE_DIR)

mark_as_advanced(GMP_INCLUDE_DIRS GMP_LIBRARIES)
